# Generated by Django 4.0.3 on 2022-12-30 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rmsoft', '0003_alter_client_client_phone_number_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='company_phone_number',
            new_name='company_tel_number',
        ),
    ]
